#!/bin/bash

cp ./build/libs/lephora-server-*.jar acceptance-test/
docker build -t lephora-server:latest acceptance-test/
docker rm -f lephora
docker run --name=lephora -d -p 18080:8080 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=123456 -e POSTGRES_DB=lephora postgres:14.5
docker run -d --network=container:lephora lephora-server:latest
