kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: test and build
    image: quay.io/testcontainers/dind-drone-plugin
    environment:
      CI_WORKSPACE: "/drone/src"
    settings:
      cmd: ./gradlew clean checkstyleMain checkstyleTest ci-test bootJar
      build_image: gradle:7.6-jdk17-alpine
      prefetch_images:
        - "gradle:7.6-jdk17-alpine"
        - "postgres:14.5"
    volumes:
      - name: docker_socket
        path: /var/run
  - name: acceptance-test
    image: docker:dind
    privileged: true
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      CONTRACT_ENABLE: true
      CONTRACT_REPO_OWNER: Lephora
      CONTRACT_REPO_NAME: lephora-api
      CONTRACT_REPO_BRANCH: main
      CONTRACT_REPO_PATH: lephora-server-api.yaml
      DRONE_GIT_USERNAME: NoodleCookie
      DRONE_GIT_PASSWORD:
        from_secret: github_token
      DEFAULT_HOST: http://127.0.0.1:18080
    volumes:
      - name: host_docker_socket
        path: /var/run/docker.sock
    commands:
      - echo "start acceptance test"
      - apk update && apk --no-cache add go git bash
      - bash ./acceptance-test/setup act-${DRONE_COMMIT}-db act-${DRONE_COMMIT}
      - git clone https://github.com/Lephora/support-kit.git
      - cd support-kit/acceptance-test/core/
      - go build -o acceptance-test main.go
      - chmod +x acceptance-test
      - mv acceptance-test ..
      - cd ..
      - ./acceptance-test assert --roots testdata
  - name: clean
    image: docker:dind
    privileged: true
    network_mode: host
    volumes:
      - name: host_docker_socket
        path: /var/run/docker.sock
    when:
      status:
        - success
        - failure
    commands:
      - apk update && apk --no-cache add bash
      - bash ./acceptance-test/clean act-${DRONE_COMMIT}-db act-${DRONE_COMMIT}
services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: docker_socket
        path: /var/run

volumes:
  - name: docker_socket
    temp: { }
  - name: host_docker_socket
    host:
      path: /var/run/docker.sock
