kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: build & unitTest
    image: gradle:7.6-jdk17-alpine
    commands:
      - ./gradlew bootJar
      - ./gradlew clean checkstyleMain checkstyleTest
      - ./gradlew clean ci-test
