--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5 (Debian 14.5-2.pgdg110+2)
-- Dumped by pg_dump version 14.5 (Debian 14.5-2.pgdg110+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: lephora; Type: DATABASE; Schema: -; Owner: postgres
--

ALTER DATABASE lephora OWNER TO postgres;

\connect lephora

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: commodity_sku_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.commodity_sku_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.commodity_sku_seq OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: commodity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.commodity (
    sku text DEFAULT lpad((nextval('public.commodity_sku_seq'::regclass))::text, 6, '0'::text) NOT NULL,
    title text NOT NULL,
    description text,
    price numeric(10,2) DEFAULT 0.00,
    price_unit text DEFAULT 'RMB'::text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by text NOT NULL,
    last_modified_at timestamp with time zone NOT NULL,
    last_modified_by text NOT NULL
);


ALTER TABLE public.commodity OWNER TO postgres;

--
-- Name: commodity_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.commodity_image (
    id bigint NOT NULL,
    url text NOT NULL,
    commodity_sku text NOT NULL,
    alternative_text character varying(200)
);


ALTER TABLE public.commodity_image OWNER TO postgres;

--
-- Name: commodity_image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.commodity_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commodity_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO postgres;

--
-- Data for Name: commodity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.commodity (sku, title, description, price, price_unit, created_at, created_by, last_modified_at, last_modified_by) FROM stdin;
000001	lephora	from lephora	52.09	RMB	2023-03-05 02:32:05.641377+00	admin	2023-03-05 02:32:05.641377+00	tester
000002	vmware	from dell	10080.45	RMB	2023-03-05 02:32:42.00209+00	admin	2023-03-05 02:32:42.00209+00	tester
000003	terence lam	from HongKong	99999.99	RMB	2023-03-05 02:33:41.154029+00	admin	2023-03-05 02:33:41.154029+00	fans
\.


--
-- Data for Name: commodity_image; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.commodity_image (id, url, commodity_sku, alternative_text) FROM stdin;
1	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000001	tw sample 1
2	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000001	tw sample 2
3	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000001	tw sample 3
4	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000001	tw sample 4
5	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000001	tw sample 5
6	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000003	tw sample 1
7	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000003	tw sample 2
8	https://thoughtworks.okta.com/fs/bco/1/fs01mng2b3qwVhCW70h8	000003	tw sample 3
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	001	create init table	SQL	V001__create_init_table.sql	-1778737749	postgres	2023-03-05 10:30:06.079289	28	t
2	002	drop init table and create commodity table	SQL	V002__drop_init_table_and_create_commodity_table.sql	1915771759	postgres	2023-03-05 10:30:06.166467	39	t
3	003	create commodity image table	SQL	V003__create_commodity_image_table.sql	436304973	postgres	2023-03-05 10:30:06.267441	20	t
\.


--
-- Name: commodity_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.commodity_image_id_seq', 1, false);


--
-- Name: commodity_sku_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.commodity_sku_seq', 1, false);


--
-- Name: commodity_image commodity_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commodity_image
    ADD CONSTRAINT commodity_image_pkey PRIMARY KEY (id);


--
-- Name: commodity commodity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commodity
    ADD CONSTRAINT commodity_pkey PRIMARY KEY (sku);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: commodity_image fkf37hd6a9opqt363t60ey7vu6y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commodity_image
    ADD CONSTRAINT fkf37hd6a9opqt363t60ey7vu6y FOREIGN KEY (commodity_sku) REFERENCES public.commodity(sku);


--
-- PostgreSQL database dump complete
--

